<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AITeam</AssemblyName>
    <RootNamespace>AITeam</RootNamespace>
    <Version>0.2.0-alpha.2</Version>
    <FileVersion>0.2.0.2</FileVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
